universe = docker
docker_image = gcr.io/gem5-test/ubuntu-20.04_all-dependencies

log = gcr.log
error = gcr.err
output = gcr.out

executable = build_m5ops.sh

environment = "TERM=xterm-256color"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = gem5/
transfer_output_files = util/m5/m5_build.tar

request_cpus = 8
request_memory = 20GB
request_disk = 20GB

stream_output = True

queue 1
